> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [1]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sethufleck/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/sethufleck/numpy-array-operations


'https://jovian.com/sethufleck/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [2]:
import numpy as np

In [6]:
# List of functions explained 
function1 = np.concatenate  # (concatenates two or more arrays along a specified axis. Combine data from multiple sources)
function2 = np.transpose # (Transform row-based data into column-based data, and vice versa)
function3 = np.unique   # (Identify and count unique values in an array, or to remove duplicates from an array)
function4 = np.reshape # (reshapes an array into a new shape without changing its data. Converting between 1D, 2D, and higher-dimensional arrays)
function5 = np.sort   # (The elements of an array along a specified axis.Order data in ascending or descending order)

## Function 1 - np.concatenate 

Concatenates two or more arrays along a specified axis. Combine data from multiple sources.

In [8]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Explanation about example

In [3]:
# Example 2 - working
arr1 = [[1, 2, 9], 
        [3, 4., 0]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  9.,  5.,  6.,  7.],
       [ 3.,  4.,  0.,  8.,  9., 10.]])

In [5]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = np.concatenate((arr1, arr2), axis=0)

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Explanation about example

In [4]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

### concatenate two arrays arr1 and arr2 along axis 0 using the np.concatenate function. 
#### The two arrays have different shapes and this will result in an error.

#### The shape of arr1 is (2, 2) and the shape of arr2 is (2, 3).

Explanation about example (why it breaks and how to fix it)

### To fix this error, we need to make sure that the arrays have the same shape along the concatenation axis. This could involve reshaping the arrays or adding padding as necessary.

Some closing comments about when to use this function.

In [7]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sethufleck/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/sethufleck/numpy-array-operations


'https://jovian.com/sethufleck/numpy-array-operations'

## Function 2 - np.transpose 

Transform row-based data into column-based data, and vice versa

In [9]:
# Example 1 - working
arr = np.array([1, 2, 3, 4])
arr_transposed = np.transpose(arr)

print(arr_transposed)

[1 2 3 4]


Explanation about example

In [10]:
# Example 2 - working
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr_transposed = np.transpose(arr)

print(arr_transposed)

[[1 3 5]
 [2 4 6]]


Explanation about example

In [11]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_transposed = np.transpose(arr, (0, 2, 1))

print(arr_transposed)

[[[1 3]
  [2 4]]

 [[5 7]
  [6 8]]]


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

##### It allows you to transpose an array in a variety of ways, including swapping the order of dimensions, reversing the order of dimensions, or even just transposing a 1D array to leave it unchanged.

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sethufleck/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/sethufleck/numpy-array-operations


'https://jovian.com/sethufleck/numpy-array-operations'

## Function 3 - np.unique   


Identify and count unique values in an array, or to remove duplicates from an array

In [14]:
# Example 1 - working
arr = np.array([1, 2, 2, 3, 3, 3, 4, 5, 5])
unique_arr = np.unique(arr)

print(unique_arr)

[1 2 3 4 5]


Explanation about example

In [15]:
# Example 2 - working
arr = np.array([[1, 2], [2, 3], [3, 4], [1, 2], [4, 5]])
unique_arr = np.unique(arr, axis=0)

print(unique_arr)

[[1 2]
 [2 3]
 [3 4]
 [4 5]]


Explanation about example

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([[1, 2], [2, 3], [3, 4], [1, 2], [4, 5]])
unique_arr = np.unique(arr.flatten())

print(unique_arr)

[1 2 3 4 5]


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

##### Removing duplicates: Remove the duplicates, data cleaning and preprocessing.

##### Identifying unique rows: Identify the unique rows to remove duplicates or to count the number of distinct data points.

##### Counting the frequency of elements: Count the number of times each element appears.

##### Mapping categorical variables: If you have a categorical variable in your data (e.g., colors, genders).

In [17]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sethufleck/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/sethufleck/numpy-array-operations


'https://jovian.com/sethufleck/numpy-array-operations'

## Function 4 - np.reshape 

Reshapes an array into a new shape without changing its data. Converting between 1D, 2D, and higher-dimensional arrays)


In [18]:
# Example 1 - working
arr = np.arange(12)
reshaped_arr = np.reshape(arr, (4, 3))

print(reshaped_arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Explanation about example

In [19]:
# Example 2 - working
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
flattened_arr = np.reshape(arr, -1)

print(flattened_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Explanation about example

In [24]:
# Example 3 - breaking (to illustrate when it breaks)

arr = np.array([1, 2, 3, 4])
column_vector = np.reshape(arr, (-1, 1))

print(column_vector)

[[1]
 [2]
 [3]
 [4]]


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

#### Changing the shape of an array,Flattening an array,Reshaping arrays. 

#### It can help you to manipulate arrays to better suit.

In [25]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sethufleck/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/sethufleck/numpy-array-operations


'https://jovian.com/sethufleck/numpy-array-operations'

## Function 5 - np.sort   

The elements of an array along a specified axis.Order data in ascending or descending order

In [26]:
# Example 1 - working
arr = np.array([3, 1, 4, 2])
sorted_arr = np.sort(arr)

print(sorted_arr)

[1 2 3 4]


Explanation about example

In [27]:
# Example 2 - working
arr = np.array([3, 1, 4, 2])
sorted_arr = np.sort(arr)[::-1]

print(sorted_arr)

[4 3 2 1]


Explanation about example

In [28]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([[3, 1, 4], [2, 5, 1]])
sorted_arr = np.sort(arr, axis=1)

print(sorted_arr)

[[1 3 4]
 [1 2 5]]


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

#### Sorting arrays,Sorting structured arrays,Sorting in place
#### It can help you to sort and organize your data, and to make your code more efficient and readable. Whether you are working with simple arrays or complex data structures.

In [29]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sethufleck/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/sethufleck/numpy-array-operations


'https://jovian.com/sethufleck/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>